import { SOUND_LIBRARY, SOUND_LIST } from '../../metronome/sounds';
import { TWaves } from '../../types';
import { ISettingsUpdater } from './ISettingsUpdater';
import { Setting } from './Setting';
import { SettingsButton } from './SettingsButton';
import { SettingsPlaybackVolume } from './SettingsPlaybackVolume';
import { SettingsSection } from './SettingsSection';

export const SettingsPlayback = ({
  settings,
  updateSettings,
}: ISettingsUpdater) => {
  const waveTypes: TWaves[] = ['sawtooth', 'sine', 'triangle', 'square'];

  return (
    <SettingsSection name="Playback">
      <SettingsPlaybackVolume {...{ settings, updateSettings }} />
      <Setting
        label="Sound"
        description="Choose a sound from our library or use an oscillator."
      >
        <select
          value={
            settings.soundType === 'oscillator'
              ? 'oscillator'
              : settings.customSound?.id
          }
          onChange={(e: React.ChangeEvent<HTMLSelectElement>) => {
            const value = e.target.value;
            if (value === 'oscillator') {
              updateSettings({ soundType: 'oscillator' });
            } else {
              const soundId = value as keyof typeof SOUND_LIBRARY;
              updateSettings({
                soundType: 'sample',
                customSound: SOUND_LIBRARY[soundId],
              });
            }
          }}
          name="sound"
          className="bg-zinc-200 dark:bg-zinc-800"
        >
          <option value="oscillator">OSCILLATOR</option>
          {SOUND_LIST.map((sound) => (
            <option key={sound.id} value={sound.id}>
              {sound.name.toLocaleUpperCase()}
            </option>
          ))}
        </select>
      </Setting>
      <Setting
        label="Oscillator Type"
        description="Change the kind of wave that your metronome uses."
        disabled={settings.soundType !== 'oscillator'}
      >
        <select
          value={settings.wave}
          onChange={(e: React.ChangeEvent<HTMLSelectElement>) => {
            updateSettings({ wave: e.target.value as TWaves });
          }}
          name="wave"
          className="bg-zinc-200 dark:bg-zinc-800"
        >
          {waveTypes.map((type) => (
            <option key={type} value={type}>
              {type.toLocaleUpperCase()}
            </option>
          ))}
        </select>
      </Setting>
      <Setting
        label="Play Extra Beat"
        description="Clicktrack will play the downbeat of an extra measure if this setting is enabled."
      >
        <SettingsButton
          onClick={() => {
            updateSettings({
              playExtraBeat: !settings.playExtraBeat,
            });
          }}
        >
          {settings.playExtraBeat ? 'On' : 'Off'}
        </SettingsButton>
      </Setting>
      <Setting
        label="Fade Out Sound"
        description="If you are using a sound generated by an oscillator, Clicktrack will soften the sound by fading the volume out."
      >
        <SettingsButton
          onClick={() => {
            updateSettings({
              fadeOutSound: !settings.fadeOutSound,
            });
          }}
        >
          {settings.fadeOutSound ? 'On' : 'Off'}
        </SettingsButton>{' '}
      </Setting>
    </SettingsSection>
  );
};
