import { ISettingsUpdater } from './ISettingsUpdater';
import { Setting } from './Setting';
import { SettingsButton } from './SettingsButton';
import { SettingsPlaybackVolume } from './SettingsPlaybackVolume';
import { SettingsSection } from './SettingsSection';

export const SettingsPlayback = ({
  settings,
  updateSettings,
}: ISettingsUpdater) => {
  return (
    <SettingsSection name="Playback">
      <SettingsPlaybackVolume {...{ settings, updateSettings }} />
      <Setting
        label="Fade Out Sound"
        description="If you are using a sound generated by an oscillator, Clicktrack will soften the sound by fading the volume out."
      >
        <SettingsButton
          onClick={() => {
            updateSettings({
              fadeOutSound: !settings.fadeOutSound,
            });
          }}
        >
          {settings.fadeOutSound ? 'On' : 'Off'}
        </SettingsButton>{' '}
      </Setting>
    </SettingsSection>
  );
};
