import { ISettingsUpdater } from './ISettingsUpdater';
import { Setting } from './Setting';
import { SettingsButton } from './SettingsButton';
import { SettingsPlaybackVolume } from './SettingsPlaybackVolume';
import { SettingsSection } from './SettingsSection';

export const SettingsPlayback = ({
  settings,
  updateSettings,
}: ISettingsUpdater) => {
  return (
    <SettingsSection name="Playback">
      <SettingsPlaybackVolume {...{ settings, updateSettings }} />
      <Setting
        label="Play Extra Beat"
        description="Clicktrack will play the downbeat of an extra measure if this setting is enabled."
      >
        <SettingsButton
          onClick={() => {
            updateSettings({
              playExtraBeat: !settings.playExtraBeat,
            });
          }}
        >
          {settings.playExtraBeat ? 'On' : 'Off'}
        </SettingsButton>
      </Setting>
      <Setting
        label="Fade Out Sound"
        description="If you are using a sound generated by an oscillator, Clicktrack will soften the sound by fading the volume out."
      >
        <SettingsButton
          onClick={() => {
            updateSettings({
              fadeOutSound: !settings.fadeOutSound,
            });
          }}
        >
          {settings.fadeOutSound ? 'On' : 'Off'}
        </SettingsButton>{' '}
      </Setting>
    </SettingsSection>
  );
};
